import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`min-h-screen bg-slate-50 flex flex-col ${inter.className}`}>
          <main className='w-full p-4'>
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  )
}
